### ISSUE TITLE
Integer type error

### ISSUE THREAD

**Issue by Xathz** [ObsidianMinor/Gfycat.Net#7]
I have tried to upload various MP4 videos and it fails uploading any of them with ```Input string '299.0' is not a valid integer. Path 'gfyItem.numFrames', line 1, position 1747.```

Even though the Gfycat documentation always shows `numFrames` returning as an int, it seems to sometimes return a double.

I changed the int to a double and it seems to work fine.

**Comment by ObsidianMinor** [comment]
Fixed in #8
